name: "Github Actions"
description: This is to create a new GHA
title: "Sample form for GitHub actions "
body:
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: dependency-explanation
    attributes:
      label: If Yes, please explain
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we are creating a sorter that will move closed issues and PRs to the correct column by their labels when they are closed."
      placeholder: |
        Clearly state the purpose of this issue in 2 sentences or less!
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Action Items/Pseudo-code"
      options:
          - label:  "When an issue/PR is closed:"
          - label:  "If the issue/PR contains a label from the hard label list:"
          - label:  "Place the issue/PR in the column marked 'Done'."
          - label:  "Else if the issue/PR contains a label from the soft label list:"
          - label:  "If the issue also contains a label from the soft label counter list:"
          - label:  "Place the issue/PR in the column marked 'UAT'"
          - label:  "Else:"
          - label:  "Place the issue/PR in the column marked 'Done'."
          - label:  "Else:"
          - label:  "Place the issue/PR in the column marked 'UAT'."
          - label:  "Hard label list: any labels involving refactoring"
          - label:  "Soft label list: 'role: back end' label, 'Feature: Analytics'"
          - label:  "Soft label counter-list: 'role: front end'"
  - type: textarea
    id: Resources
    attributes:
      label: "Resources/Instructions"
      description: "Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
        Note that you might want to do something outside the scope of the above pseudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: This is to create a new GHA
      options:
        - label: I have searched the existing issues
          required: true